name: Build and upload
on: [push]
defaults:
  run:
    shell: bash
jobs:
  Build:
    runs-on: macos-latest
    steps:
      - name: Clone fermenter
        uses: actions/checkout@master
        with:
          repository: ferment-pkg/fermenter
      - name: Install Fermenter
        run: install bin/darwin/fermenter /usr/local/bin
      - name: Clone ferment
        uses: actions/checkout@master
        with:
          repository: ferment-pkg/ferment
          path: /usr/local/ferment/
          submodules: recursive
      - name: Install Ferment
        run: sh install.sh
      - id: files
        uses: jitterbit/get-changed-files@v1
      - name: Ferment barrells
        run: |
          for changed_file in ${{ steps.files.outputs.all }}; do
            fermenter build ${changed_file%.py} --barrells=/usr/local/ferment/Barrells
          done
      - name: Finish
        run: ferment upgrade
