name: Build and upload
on: [push]
defaults:
  run:
    shell: bash
jobs:
  Build:
    runs-on: macos-latest
    steps:
      - name: Clone fermenter
        uses: actions/checkout@master
        with:
          repository: ferment-pkg/fermenter
      - name: Install Fermenter
        run: install bin/darwin/fermenter /usr/local/bin
      # - name: Clone ferment
      #   uses: actions/checkout@master
      #   with:
      #     repository: ferment-pkg/ferment
      #     path: /Users/runner/work/ferment
      #     submodules: recursive
      - name: Clone Ferment
        run: git clone --depth 1 --recursive https://github.com/ferment-pkg/ferment /Users/runner/work/ferment
      - name: Install Ferment
        run: sh install.sh
      - id: files
        uses: jitterbit/get-changed-files@v1
      - name: ls
        run: ls -la /Users/runner/work/Barrells/Barrells
      - name: Ferment barrells
        run: |
          for changed_file in ${{ steps.files.outputs.all }}; do
            if [[ $changed_file != *.py ]]; then
              echo "Skipping $changed_file"
              continue
            fi
            fermenter build ${changed_file%.py} --barrells=/Users/runner/work/Barrells/Barrells
          done
      - name: Finish
        run: ferment upgrade
