name: Build And Test
on: [pull_request]
jobs:
  Build:
    runs-on: macos-latest
    steps:
      - name: Get Branch Name
        uses: EthanSK/git-branch-name-action@v1
      - run: git clone --branch ${GIT_BRANCH_NAME} https://github.com/ferment-pkg/Barrells .
      - name: Clone fermenter
        run: git clone --depth 1 --recursive https://github.com/ferment-pkg/fermenter /Users/runner/work/Barrells/fermenter
        # uses: actions/checkout@master
        # with:
        #   repository: ferment-pkg/fermenter
        #   path: /Users/runner/work/Barrells/fermenter

      - name: Install Fermenter
        run: install /Users/runner/work/Barrells/fermenter/bin/darwin/fermenter /usr/local/bin
      # - name: Clone ferment
      #   uses: actions/checkout@master
      #   with:
      #     repository: ferment-pkg/ferment
      #     path: /Users/runner/work/ferment
      #     submodules: recursive
      - name: Clone Ferment
        run: git clone --depth 1 --recursive https://github.com/ferment-pkg/ferment /Users/runner/work/Barrells/ferment
      - name: Install Ferment
        run: cd /Users/runner/work/Barrells/ferment && sh install.sh
      - id: files
        uses: jitterbit/get-changed-files@v1
      - run: ls ~/work/Barrells/
      - run: ls ~/work/Barrells/Barrells
      - run: ls ~/work/Barrells/ferment
      - name: Ferment barrells
        run: |
          for changed_file in ${{ steps.files.outputs.all }}; do
            if [[ $changed_file != *.py ]]; then
              echo "Skipping $changed_file"
              continue
            fi
            if [[ "$changed_file" == "index.py" ]];then
              echo "Skipping $changed_file"
              continue
            fi
            echo PKG ${changed_file%.py}
            PATH="$PATH:/Users/runner/work/Barrells/ferment" fermenter test ${changed_file%.py} --barrells=/Users/runner/work/Barrells/Barrells
          done